#!/usr/bin/python
###############################################################################
#                                                                             #
# collecty - A system statistics collection daemon for IPFire                 #
# Copyright (C) 2012 IPFire development team                                  #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

import optparse
import sys

import collecty

# Parse command line options.
op = optparse.OptionParser(usage="usage: %prog [options] <configfile1> ... <configfileN>")
op.add_option("-d", "--daemon", action="store_true", default=False,
		help="Run as a daemon in background.")
(options, configfiles) = op.parse_args()

# Initialize the application.
c = collecty.Collecty()

# Run.
c.run()

sys.exit(0)
