#!/usr/bin/python3
###############################################################################
#                                                                             #
# collecty - A system statistics collection daemon for IPFire                 #
# Copyright (C) 2012 IPFire development team                                  #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

import optparse
import sys

import collecty.daemon

# Parse command line options.
op = optparse.OptionParser(usage="usage: %prog [options]")
op.add_option("-d", "--debug", action="store_true", default=False,
		help="Enable debug logging.")
(options, args) = op.parse_args()

# Initialize the settings for this Collecty instance.
settings = {
	"debug" : options.debug,
}

# Initialize the application.
c = collecty.daemon.Daemon(**settings)

# Run.
c.run()

sys.exit(0)
