#!/usr/bin/python3
###############################################################################
#                                                                             #
# collecty - A system statistics collection daemon for IPFire                 #
# Copyright (C) 2020 IPFire development team                                  #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

import argparse
import collecty.daemon

from collecty.i18n import _

def main():
	parser = argparse.ArgumentParser(
		description=_("Collecty Daemon"),
	)

	# Global configuration flags
	parser.add_argument("--debug", action="store_true",
		help=_("Enable debug output"),
	)

	# Parse CLI arguments
	args = parser.parse_args()

	# Initialise the daemon
	daemon = collecty.daemon.Daemon(debug=args.debug)

	# Run it
	try:
		daemon.run()
	except KeyboardInterrupt:
		pass

# Call main function
main()
